package com.bill99.ian.dao;

import com.bill99.ian.entity.SysAuthoritiesResources;
import java.util.List;

public interface SysAuthoritiesResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities_resources
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities_resources
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    int insert(SysAuthoritiesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities_resources
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    SysAuthoritiesResources selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities_resources
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    List<SysAuthoritiesResources> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities_resources
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    int updateByPrimaryKey(SysAuthoritiesResources record);
    
    List<SysAuthoritiesResources> findByAuthorityId(String authorityId);
}