package com.bill99.ian.dao;

import com.bill99.ian.entity.SysRolesAuthorities;
import java.util.List;

public interface SysRolesAuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_authorities
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_authorities
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    int insert(SysRolesAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_authorities
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    SysRolesAuthorities selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_authorities
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    List<SysRolesAuthorities> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_authorities
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    int updateByPrimaryKey(SysRolesAuthorities record);
}