package com.bill99.ian.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.busi_type
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amt
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    private Integer amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_no
     *
     * @param orderNo the value for order.order_no
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.busi_type
     *
     * @return the value of order.busi_type
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.busi_type
     *
     * @param busiType the value for order.busi_type
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amt
     *
     * @return the value of order.amt
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public Integer getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amt
     *
     * @param amt the value for order.amt
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public void setAmt(Integer amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbggenerated Thu Dec 17 11:22:16 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}