package com.bill99.ian.entity;

import java.io.Serializable;

public class SysAuthoritiesResources implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 8480501656000535863L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities_resources.ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Long id;

    private SysAuthorities sysAuthorities;  
    private SysResources sysResources;

    public SysAuthorities getSysAuthorities() {
		return sysAuthorities;
	}

	public void setSysAuthorities(SysAuthorities sysAuthorities) {
		this.sysAuthorities = sysAuthorities;
	}

	public SysResources getSysResources() {
		return sysResources;
	}

	public void setSysResources(SysResources sysResources) {
		this.sysResources = sysResources;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities_resources.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer enabled;

    public SysAuthoritiesResources() {  
    }  
  
    public SysAuthoritiesResources(long id) {  
        this.id = id;  
    }  
  
    public SysAuthoritiesResources(long id, SysAuthorities sysAuthorities,  
            SysResources sysResources, Integer enabled) {  
        this.id = id;  
        this.sysAuthorities = sysAuthorities;  
        this.sysResources = sysResources;  
        this.enabled = enabled;  
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities_resources.ID
     *
     * @return the value of sys_authorities_resources.ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities_resources.ID
     *
     * @param id the value for sys_authorities_resources.ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities_resources.ENABLED
     *
     * @return the value of sys_authorities_resources.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities_resources.ENABLED
     *
     * @param enabled the value for sys_authorities_resources.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}