package com.bill99.ian.entity;

import java.io.Serializable;
import java.util.Set;

public class SysRoles implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 2144692353640974540L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_NAME
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_DESC
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ISSYS
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.MODULE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String module;
    
    private Set<SysUsersRoles> sysUsersRoles;  
    private Set<SysRolesAuthorities> sysRolesAuthorities;
    
    public SysRoles() {  
    }  
  
    public SysRoles(String roleId) {  
        this.roleId = roleId;  
    }  
      
    public SysRoles(String roleId, String roleName, String roleDesc) {  
        this.roleId = roleId;  
        this.roleName = roleName;  
        this.roleDesc = roleDesc;  
    }  
      
    public SysRoles(String roleId, String roleName, String roleDesc,  
            Integer enabled, Integer issys, String module) {  
        this.roleId = roleId;  
        this.roleName = roleName;  
        this.roleDesc = roleDesc;  
        this.enabled = enabled;  
        this.issys = issys;  
        this.module = module;  
    }
    
    public SysRoles(String roleId, String roleName, String roleDesc,  
            Integer enabled, Integer issys, String module, Set<SysUsersRoles> sysUsersRoles,  
            Set<SysRolesAuthorities> sysRolesAuthorities) {  
        this.roleId = roleId;  
        this.roleName = roleName;  
        this.roleDesc = roleDesc;  
        this.enabled = enabled;  
        this.issys = issys;  
        this.module = module;  
        this.sysUsersRoles = sysUsersRoles;  
        this.sysRolesAuthorities = sysRolesAuthorities;  
    }
    
    public Set<SysUsersRoles> getSysUsersRoles() {
		return sysUsersRoles;
	}

	public void setSysUsersRoles(Set<SysUsersRoles> sysUsersRoles) {
		this.sysUsersRoles = sysUsersRoles;
	}

	public Set<SysRolesAuthorities> getSysRolesAuthorities() {
		return sysRolesAuthorities;
	}

	public void setSysRolesAuthorities(Set<SysRolesAuthorities> sysRolesAuthorities) {
		this.sysRolesAuthorities = sysRolesAuthorities;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_ID
     *
     * @return the value of sys_roles.ROLE_ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_ID
     *
     * @param roleId the value for sys_roles.ROLE_ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_NAME
     *
     * @return the value of sys_roles.ROLE_NAME
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_NAME
     *
     * @param roleName the value for sys_roles.ROLE_NAME
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_DESC
     *
     * @return the value of sys_roles.ROLE_DESC
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_DESC
     *
     * @param roleDesc the value for sys_roles.ROLE_DESC
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ENABLED
     *
     * @return the value of sys_roles.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ENABLED
     *
     * @param enabled the value for sys_roles.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ISSYS
     *
     * @return the value of sys_roles.ISSYS
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ISSYS
     *
     * @param issys the value for sys_roles.ISSYS
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.MODULE
     *
     * @return the value of sys_roles.MODULE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.MODULE
     *
     * @param module the value for sys_roles.MODULE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setModule(String module) {
        this.module = module;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((enabled == null) ? 0 : enabled.hashCode());
		result = prime * result + ((issys == null) ? 0 : issys.hashCode());
		result = prime * result + ((module == null) ? 0 : module.hashCode());
		result = prime * result
				+ ((roleDesc == null) ? 0 : roleDesc.hashCode());
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode());
		result = prime * result
				+ ((roleName == null) ? 0 : roleName.hashCode());
		result = prime
				* result
				+ ((sysRolesAuthorities == null) ? 0 : sysRolesAuthorities
						.hashCode());
		result = prime * result
				+ ((sysUsersRoles == null) ? 0 : sysUsersRoles.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SysRoles other = (SysRoles) obj;
		if (enabled == null) {
			if (other.enabled != null)
				return false;
		} else if (!enabled.equals(other.enabled))
			return false;
		if (issys == null) {
			if (other.issys != null)
				return false;
		} else if (!issys.equals(other.issys))
			return false;
		if (module == null) {
			if (other.module != null)
				return false;
		} else if (!module.equals(other.module))
			return false;
		if (roleDesc == null) {
			if (other.roleDesc != null)
				return false;
		} else if (!roleDesc.equals(other.roleDesc))
			return false;
		if (roleId == null) {
			if (other.roleId != null)
				return false;
		} else if (!roleId.equals(other.roleId))
			return false;
		if (roleName == null) {
			if (other.roleName != null)
				return false;
		} else if (!roleName.equals(other.roleName))
			return false;
		if (sysRolesAuthorities == null) {
			if (other.sysRolesAuthorities != null)
				return false;
		} else if (!sysRolesAuthorities.equals(other.sysRolesAuthorities))
			return false;
		if (sysUsersRoles == null) {
			if (other.sysUsersRoles != null)
				return false;
		} else if (!sysUsersRoles.equals(other.sysUsersRoles))
			return false;
		return true;
	}
}