package com.bill99.ian.entity;

import java.io.Serializable;
import java.util.Set;

public class SysResources implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7666502957897571714L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_NAME
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_DESC
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_STRING
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String resourceString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.PRIORITY
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.ISSYS
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.MODULE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private String module;
    
    private Set<SysAuthoritiesResources> sysAuthoritiesResourceses ;
    
    public SysResources() {  
    }  
  
    public SysResources(String resourceId) {  
        this.resourceId = resourceId;  
    }  
  
    public SysResources(String resourceId, String resourceName,  
            String resourceDesc, String resourceType, String resourceString,  
            Integer priority, Integer enabled, Integer issys, String module,  
            Set<SysAuthoritiesResources> sysAuthoritiesResourceses) {  
        this.resourceId = resourceId;  
        this.resourceName = resourceName;  
        this.resourceDesc = resourceDesc;  
        this.resourceType = resourceType;  
        this.resourceString = resourceString;  
        this.priority = priority;  
        this.enabled = enabled;  
        this.issys = issys;  
        this.module = module;  
        this.sysAuthoritiesResourceses = sysAuthoritiesResourceses;  
    }
    
    public Set<SysAuthoritiesResources> getSysAuthoritiesResourceses() {
		return sysAuthoritiesResourceses;
	}

	public void setSysAuthoritiesResourceses(
			Set<SysAuthoritiesResources> sysAuthoritiesResourceses) {
		this.sysAuthoritiesResourceses = sysAuthoritiesResourceses;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_ID
     *
     * @return the value of sys_resources.RESOURCE_ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_ID
     *
     * @param resourceId the value for sys_resources.RESOURCE_ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_NAME
     *
     * @return the value of sys_resources.RESOURCE_NAME
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_NAME
     *
     * @param resourceName the value for sys_resources.RESOURCE_NAME
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_DESC
     *
     * @return the value of sys_resources.RESOURCE_DESC
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_DESC
     *
     * @param resourceDesc the value for sys_resources.RESOURCE_DESC
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_TYPE
     *
     * @return the value of sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_TYPE
     *
     * @param resourceType the value for sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_STRING
     *
     * @return the value of sys_resources.RESOURCE_STRING
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getResourceString() {
        return resourceString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_STRING
     *
     * @param resourceString the value for sys_resources.RESOURCE_STRING
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setResourceString(String resourceString) {
        this.resourceString = resourceString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.PRIORITY
     *
     * @return the value of sys_resources.PRIORITY
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.PRIORITY
     *
     * @param priority the value for sys_resources.PRIORITY
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.ENABLED
     *
     * @return the value of sys_resources.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.ENABLED
     *
     * @param enabled the value for sys_resources.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.ISSYS
     *
     * @return the value of sys_resources.ISSYS
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.ISSYS
     *
     * @param issys the value for sys_resources.ISSYS
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.MODULE
     *
     * @return the value of sys_resources.MODULE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.MODULE
     *
     * @param module the value for sys_resources.MODULE
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setModule(String module) {
        this.module = module;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((enabled == null) ? 0 : enabled.hashCode());
		result = prime * result + ((issys == null) ? 0 : issys.hashCode());
		result = prime * result + ((module == null) ? 0 : module.hashCode());
		result = prime * result
				+ ((priority == null) ? 0 : priority.hashCode());
		result = prime * result
				+ ((resourceDesc == null) ? 0 : resourceDesc.hashCode());
		result = prime * result
				+ ((resourceId == null) ? 0 : resourceId.hashCode());
		result = prime * result
				+ ((resourceName == null) ? 0 : resourceName.hashCode());
		result = prime * result
				+ ((resourceString == null) ? 0 : resourceString.hashCode());
		result = prime * result
				+ ((resourceType == null) ? 0 : resourceType.hashCode());
		result = prime
				* result
				+ ((sysAuthoritiesResourceses == null) ? 0
						: sysAuthoritiesResourceses.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SysResources other = (SysResources) obj;
		if (enabled == null) {
			if (other.enabled != null)
				return false;
		} else if (!enabled.equals(other.enabled))
			return false;
		if (issys == null) {
			if (other.issys != null)
				return false;
		} else if (!issys.equals(other.issys))
			return false;
		if (module == null) {
			if (other.module != null)
				return false;
		} else if (!module.equals(other.module))
			return false;
		if (priority == null) {
			if (other.priority != null)
				return false;
		} else if (!priority.equals(other.priority))
			return false;
		if (resourceDesc == null) {
			if (other.resourceDesc != null)
				return false;
		} else if (!resourceDesc.equals(other.resourceDesc))
			return false;
		if (resourceId == null) {
			if (other.resourceId != null)
				return false;
		} else if (!resourceId.equals(other.resourceId))
			return false;
		if (resourceName == null) {
			if (other.resourceName != null)
				return false;
		} else if (!resourceName.equals(other.resourceName))
			return false;
		if (resourceString == null) {
			if (other.resourceString != null)
				return false;
		} else if (!resourceString.equals(other.resourceString))
			return false;
		if (resourceType == null) {
			if (other.resourceType != null)
				return false;
		} else if (!resourceType.equals(other.resourceType))
			return false;
		if (sysAuthoritiesResourceses == null) {
			if (other.sysAuthoritiesResourceses != null)
				return false;
		} else if (!sysAuthoritiesResourceses
				.equals(other.sysAuthoritiesResourceses))
			return false;
		return true;
	}
}