package com.bill99.ian.entity;

import java.io.Serializable;

public class SysRolesAuthorities implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -6359550469849162638L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_authorities.ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Long id;

    private SysRoles sysRoles;

    private SysAuthorities sysAuthorities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_authorities.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    private Integer enabled;

    public SysRolesAuthorities(){
    }
    
    public SysRolesAuthorities(Long id, SysRoles sysRoles, SysAuthorities sysAuthorities, Integer enabled){
    	this.id = id;
    	this.sysAuthorities = sysAuthorities;
    	this.sysRoles = sysRoles;
    	this.enabled = enabled;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_authorities.ID
     *
     * @return the value of sys_roles_authorities.ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_authorities.ID
     *
     * @param id the value for sys_roles_authorities.ID
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    public SysRoles getSysRoles() {
		return sysRoles;
	}

	public void setSysRoles(SysRoles sysRoles) {
		this.sysRoles = sysRoles;
	}

	public SysAuthorities getSysAuthorities() {
		return sysAuthorities;
	}

	public void setSysAuthorities(SysAuthorities sysAuthorities) {
		this.sysAuthorities = sysAuthorities;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_authorities.ENABLED
     *
     * @return the value of sys_roles_authorities.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_authorities.ENABLED
     *
     * @param enabled the value for sys_roles_authorities.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}