package com.bill99.ian.entity;

import java.io.Serializable;

public class SysUsersRoles implements Serializable {
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1602255789359814295L;

    private Long id;

    private SysUsers sysUsers;
    
    private SysRoles sysRoles;
    
    private Integer enabled;

    public SysUsersRoles(){
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SysUsers getSysUsers() {
		return sysUsers;
	}

	public void setSysUsers(SysUsers sysUsers) {
		this.sysUsers = sysUsers;
	}

	public SysRoles getSysRoles() {
		return sysRoles;
	}

	public void setSysRoles(SysRoles sysRoles) {
		this.sysRoles = sysRoles;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.ENABLED
     *
     * @return the value of sys_users_roles.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.ENABLED
     *
     * @param enabled the value for sys_users_roles.ENABLED
     *
     * @mbggenerated Fri Dec 18 17:19:16 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}